### ISSUE TITLE
Methods like loadVideoById:startSeconds:endSeconds:suggestedQuality do not work.

### ISSUE THREAD

**Issue by ddevaz** [JV17/YoutubePlayer#2]
Looks like a great library, thanks for sharing. 

It seems the methods that specify the startSeconds and endSeconds do not work. The video player view does not appear. If I use the loadVideoId method it works as expected.
e.g. 
```
- (void)viewDidLoad {
    [super viewDidLoad];
    self.player = [[YTPlayerView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width,    self.view.bounds.size.height/3)];
   
    // [self.player loadWithVideoId:@"HvRypx1lbR4"];  <--- This one works correctly.
  
    [self.player loadVideoById:@"HvRypx1lbR4" startSeconds:5.0 endSeconds:10.0 
                     suggestedQuality:kYTPlaybackQualitySmall];  // <-- This one does not work. The frame does not  appear in the view.
   
    [self.view addSubview:self.player];
}
```

Tested on Xcode 6.1.1, iOS 7.1, 8.1  (iPhone).

**Comment by JV17** [comment]
I will take a look at it and get back to you.

**Comment by JV17** [comment]
@ddevaz I have updated the library and for those functions to work properly you have to first load the player as you are doing here ` [self.player loadWithVideoId:@"HvRypx1lbR4"]; ` and then after the player has loaded you can call this other function ` [self.player loadVideoById:@"HvRypx1lbR4" startSeconds:5.0 endSeconds:10.0 suggestedQuality:kYTPlaybackQualitySmall]; ` and it should do the work for you...

I will take a bit further implementation from my part to be able to load the video directly from that second function with start seconds and end seconds, because I am gonna have to load the video first, know which function are you executing or loading the video from and then wait until the video has finished loading and then set the video to the start seconds and end seconds.. 

I don't know why Youtube doesn't actually let you load the video at first with those parameters at first, but that's the work around I found for this issue. Also, I have to mention that the `suggestedQuality` is not going to always load the quality you are setting it to.. Again, unfurtunately if the frame of the player is too small for HD it won't load the video in HD.

**Comment by ddevaz** [comment]
Okay, sounds good.
Thanks for looking into this, much appreciated.
